Ansible 2
Otus-DevOps-2023-01/coolerWhite_infra pull request #17
Opened 2023-04-07 09:03 UTC by coolerWhite

# Выполнено ДЗ №8

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - все пункты из основного ДЗ

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2023-04-07 09:05 UTC, coolerWhite commented
Добрый день.
Ошибки видел, но понять проблему не могу. Как понимаю, там конфликт файлов inventory. Или inventory.yml написан не коррестно.

2023-04-08 19:17 UTC, mrgreyves requested changes
Здравствуйте!)
Не хватает вот этого файла reddit_app_multiple_plays.yml
С инвентарем такое происходит, да

2023-04-09 09:25 UTC, coolerWhite commented
Поменял ^_^
А есть какой-то фикс для inventory?

2023-04-11 18:42 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув

2023-04-12 18:29 UTC, merged