Cloud bastion
Otus-DevOps-2023-01/coolerWhite_infra pull request #5
Opened 2023-03-12 08:28 UTC by coolerWhite

# Выполнено ДЗ №

 - [ ] Основное ДЗ
 - [ ] Задание со *

## В процессе сделано:
 - Пункт 1
 - Пункт 2

## Как запустить проект:
 - Например, запустить команду X в директории Y

## Как проверить работоспособность:
 - Например, перейти по ссылке http://localhost:8080

## PR checklist
 - [ ] Выставил label с номером домашнего задания
 - [ ] Выставил label с темой домашнего задания

2023-03-13 11:59 UTC, mrgreyves requested changes
Здравствуйте!)
Нужно обратить внимание на тесты
Много ошибок
Во время запуска тестов ВМ были включены?
Так же нужно пофиксить скрипт установки VPN

2023-03-14 17:36 UTC, coolerWhite commented
> Здравствуйте!) Нужно обратить внимание на тесты Много ошибок Во время запуска тестов ВМ были включены? Так же нужно пофиксить скрипт установки VPN

Добрый день
setupvpn.sh переделал. Писал в другом PR, но повторю. 


`как я понял, travis проверяет выполнение условий по "названию ветки". эти проверки одинаковы, что в моем репозитории, что в репозитории, которое создано в OTUS. у меня проверки проходит полностью, после чего отправляю PR. Т.к проверка моего PR может занимать какое-то время, то я удаляю все инстансы, которые использовались для ДЗ. Моя ошибка, что я удаляю инстансы, до PR в OTUS`

2023-03-16 10:22 UTC, mrgreyves approved these changes
Здравствуйте!)
Апрув ^_^
Не нужно заново поднимать всю инфраструктуру
Перед мержем нужно будет порешать возникшие конфликты

2023-03-16 20:58 UTC, coolerWhite reviewed
check

2023-03-16 21:11 UTC, coolerWhite commented
file

2023-03-16 21:11 UTC, closed without merging